mods.extendedcrafting.TableCrafting.addShapedMirrored(0, <bigreactors:reactorcreativecoolantport>, [
	[<bigreactors:reactorcasing>, <techreborn:machine_casing:2>, <techreborn:machine_casing:2>, <techreborn:machine_casing:2>, <techreborn:machine_casing:2>, <techreborn:machine_casing:2>, <techreborn:machine_casing:2>, <techreborn:machine_casing:2>, <bigreactors:reactorcasing>], 
	[<bigreactors:reactorcasing>, <techreborn:machine_casing:2>, <techreborn:part:9>, <techreborn:part:9>, <techreborn:part:9>, <techreborn:part:9>, <techreborn:part:9>, <techreborn:machine_casing:2>, <bigreactors:reactorcasing>], 
	[<bigreactors:reactorcasing>, <techreborn:machine_casing:2>, <techreborn:part:12>, <techreborn:part:12>, <techreborn:part:12>, <techreborn:part:12>, <techreborn:part:12>, <bigreactors:reactorcoolantport>, <bigreactors:reactorglass>], 
	[<bigreactors:reactorcasing>, <techreborn:machine_casing:2>, <techreborn:matter_fabricator>, <techreborn:matter_fabricator>, <techreborn:matter_fabricator>, <techreborn:matter_fabricator>, <techreborn:matter_fabricator>, <bigreactors:reactorcoolantport>, <bigreactors:reactorglass>], 
	[<bigreactors:reactorcasing>, <techreborn:machine_casing:2>, <openblocks:tank>.withTag({tank: {FluidName: "cryotheum", Amount: 16000}}), <extendedcrafting:singularity:50>, <openblocks:tank>.withTag({tank: {FluidName: "cryotheum", Amount: 16000}}), <extendedcrafting:singularity:50>, <openblocks:tank>.withTag({tank: {FluidName: "cryotheum", Amount: 16000}}), <bigreactors:reactorcoolantport>, <bigreactors:reactorglass>], 
	[<bigreactors:reactorcasing>, <techreborn:machine_casing:2>, <techreborn:matter_fabricator>, <techreborn:matter_fabricator>, <techreborn:matter_fabricator>, <techreborn:matter_fabricator>, <techreborn:matter_fabricator>, <bigreactors:reactorcoolantport>, <bigreactors:reactorglass>], 
	[<bigreactors:reactorcasing>, <techreborn:machine_casing:2>, <techreborn:part:12>, <techreborn:part:12>, <techreborn:part:12>, <techreborn:part:12>, <techreborn:part:12>, <bigreactors:reactorcoolantport>, <bigreactors:reactorglass>], 
	[<bigreactors:reactorcasing>, <techreborn:machine_casing:2>, <techreborn:part:9>, <techreborn:part:9>, <techreborn:part:9>, <techreborn:part:9>, <techreborn:part:9>, <techreborn:machine_casing:2>, <bigreactors:reactorcasing>], 
	[<bigreactors:reactorcasing>, <techreborn:machine_casing:2>, <techreborn:machine_casing:2>, <techreborn:machine_casing:2>, <techreborn:machine_casing:2>, <techreborn:machine_casing:2>, <techreborn:machine_casing:2>, <techreborn:machine_casing:2>, <bigreactors:reactorcasing>]
]);