mods.extendedcrafting.TableCrafting.addShaped(0, <thermalfoundation:upgrade:256>, [
	[<thermalfoundation:upgrade:33>, <thermalfoundation:upgrade:34>, <thermalfoundation:upgrade:35>, <ore:ingotCosmicNeutronium>, <extendedcrafting:singularity_ultimate>, <ore:ingotCosmicNeutronium>, <thermalfoundation:upgrade:35>, <thermalfoundation:upgrade:34>, <thermalfoundation:upgrade:33>], 
	[<thermalfoundation:upgrade:34>, <thermalfoundation:upgrade:35>, <ore:ingotCosmicNeutronium>, <extendedcrafting:singularity_ultimate>, <avaritia:resource:5>, <extendedcrafting:singularity_ultimate>, <ore:ingotCosmicNeutronium>, <thermalfoundation:upgrade:35>, <thermalfoundation:upgrade:34>], 
	[<thermalfoundation:upgrade:35>, <ore:ingotCosmicNeutronium>, <extendedcrafting:singularity_ultimate>, <avaritia:resource:5>, <ore:ingotInfinity>, <avaritia:resource:5>, <extendedcrafting:singularity_ultimate>, <ore:ingotCosmicNeutronium>, <thermalfoundation:upgrade:35>], 
	[<ore:ingotCosmicNeutronium>, <extendedcrafting:singularity_ultimate>, <avaritia:resource:5>, <ore:ingotInfinity>, <ore:blockInfinity>, <ore:ingotInfinity>, <avaritia:resource:5>, <extendedcrafting:singularity_ultimate>, <ore:ingotCosmicNeutronium>], 
	[<extendedcrafting:singularity_ultimate>, <avaritia:resource:5>, <ore:ingotInfinity>, <ore:blockInfinity>, <projectex:final_star>, <ore:blockInfinity>, <ore:ingotInfinity>, <avaritia:resource:5>, <extendedcrafting:singularity_ultimate>], 
	[<ore:ingotCosmicNeutronium>, <extendedcrafting:singularity_ultimate>, <avaritia:resource:5>, <ore:ingotInfinity>, <ore:blockInfinity>, <ore:ingotInfinity>, <avaritia:resource:5>, <extendedcrafting:singularity_ultimate>, <ore:ingotCosmicNeutronium>], 
	[<thermalfoundation:upgrade:35>, <ore:ingotCosmicNeutronium>, <extendedcrafting:singularity_ultimate>, <avaritia:resource:5>, <ore:ingotInfinity>, <avaritia:resource:5>, <extendedcrafting:singularity_ultimate>, <ore:ingotCosmicNeutronium>, <thermalfoundation:upgrade:35>], 
	[<thermalfoundation:upgrade:34>, <thermalfoundation:upgrade:35>, <ore:ingotCosmicNeutronium>, <extendedcrafting:singularity_ultimate>, <avaritia:resource:5>, <extendedcrafting:singularity_ultimate>, <ore:ingotCosmicNeutronium>, <thermalfoundation:upgrade:35>, <thermalfoundation:upgrade:34>], 
	[<thermalfoundation:upgrade:33>, <thermalfoundation:upgrade:34>, <thermalfoundation:upgrade:35>, <ore:ingotCosmicNeutronium>, <extendedcrafting:singularity_ultimate>, <ore:ingotCosmicNeutronium>, <thermalfoundation:upgrade:35>, <thermalfoundation:upgrade:34>, <thermalfoundation:upgrade:33>]
]);