mods.extendedcrafting.TableCrafting.addShaped(0, <draconicevolution:draconium_capacitor:2>, [
	[<avaritia:resource:6>, <ore:blockCosmicNeutronium>, <draconicevolution:draconium_capacitor>.withTag({DEUpgrades: {rfCap: 3 as byte}, Energy: 160000000}), <draconicevolution:draconium_capacitor:1>.withTag({DEUpgrades: {rfCap: 4 as byte}, Energy: 768000000}), <avaritia:resource:6>, <draconicevolution:draconium_capacitor:1>.withTag({DEUpgrades: {rfCap: 4 as byte}, Energy: 768000000}), <draconicevolution:draconium_capacitor>.withTag({DEUpgrades: {rfCap: 3 as byte}, Energy: 160000000}), <ore:blockCosmicNeutronium>, <avaritia:resource:6>], 
	[<ore:blockCosmicNeutronium>, <draconicevolution:draconium_capacitor>.withTag({DEUpgrades: {rfCap: 3 as byte}, Energy: 160000000}), <draconicevolution:draconium_capacitor:1>.withTag({DEUpgrades: {rfCap: 4 as byte}, Energy: 768000000}), <ore:blockDraconiumAwakened>, <thermalexpansion:capacitor:32000>.withTag({Energy: 25000000}), <ore:blockDraconiumAwakened>, <draconicevolution:draconium_capacitor:1>.withTag({DEUpgrades: {rfCap: 4 as byte}, Energy: 768000000}), <draconicevolution:draconium_capacitor>.withTag({DEUpgrades: {rfCap: 3 as byte}, Energy: 160000000}), <ore:blockCosmicNeutronium>], 
	[<draconicevolution:draconium_capacitor>.withTag({DEUpgrades: {rfCap: 3 as byte}, Energy: 160000000}), <draconicevolution:draconium_capacitor:1>.withTag({DEUpgrades: {rfCap: 4 as byte}, Energy: 768000000}), <ore:blockDraconiumAwakened>, <thermalexpansion:capacitor:32000>.withTag({Energy: 25000000}), <avaritia:resource:5>, <thermalexpansion:capacitor:32000>.withTag({Energy: 25000000}), <ore:blockDraconiumAwakened>, <draconicevolution:draconium_capacitor:1>.withTag({DEUpgrades: {rfCap: 4 as byte}, Energy: 768000000}), <draconicevolution:draconium_capacitor>.withTag({DEUpgrades: {rfCap: 3 as byte}, Energy: 160000000})], 
	[<draconicevolution:draconium_capacitor:1>.withTag({DEUpgrades: {rfCap: 4 as byte}, Energy: 768000000}), <ore:blockDraconiumAwakened>, <thermalexpansion:capacitor:32000>.withTag({Energy: 25000000}), <avaritia:resource:5>, <ore:ingotInfinity>, <avaritia:resource:5>, <thermalexpansion:capacitor:32000>.withTag({Energy: 25000000}), <ore:blockDraconiumAwakened>, <draconicevolution:draconium_capacitor:1>.withTag({DEUpgrades: {rfCap: 4 as byte}, Energy: 768000000})], 
	[<avaritia:resource:6>, <thermalexpansion:capacitor:32000>.withTag({Energy: 25000000}), <avaritia:resource:5>, <ore:ingotInfinity>, <enderio:block_cap_bank>, <ore:ingotInfinity>, <avaritia:resource:5>, <thermalexpansion:capacitor:32000>.withTag({Energy: 25000000}), <avaritia:resource:6>], 
	[<draconicevolution:draconium_capacitor:1>.withTag({DEUpgrades: {rfCap: 4 as byte}, Energy: 768000000}), <ore:blockDraconiumAwakened>, <thermalexpansion:capacitor:32000>.withTag({Energy: 25000000}), <avaritia:resource:5>, <ore:ingotInfinity>, <avaritia:resource:5>, <thermalexpansion:capacitor:32000>.withTag({Energy: 25000000}), <ore:blockDraconiumAwakened>, <draconicevolution:draconium_capacitor:1>.withTag({DEUpgrades: {rfCap: 4 as byte}, Energy: 768000000})], 
	[<draconicevolution:draconium_capacitor>.withTag({DEUpgrades: {rfCap: 3 as byte}, Energy: 160000000}), <draconicevolution:draconium_capacitor:1>.withTag({DEUpgrades: {rfCap: 4 as byte}, Energy: 768000000}), <ore:blockDraconiumAwakened>, <thermalexpansion:capacitor:32000>.withTag({Energy: 25000000}), <avaritia:resource:5>, <thermalexpansion:capacitor:32000>.withTag({Energy: 25000000}), <ore:blockDraconiumAwakened>, <draconicevolution:draconium_capacitor:1>.withTag({DEUpgrades: {rfCap: 4 as byte}, Energy: 768000000}), <draconicevolution:draconium_capacitor>.withTag({DEUpgrades: {rfCap: 3 as byte}, Energy: 160000000})], 
	[<ore:blockCosmicNeutronium>, <draconicevolution:draconium_capacitor>.withTag({DEUpgrades: {rfCap: 3 as byte}, Energy: 160000000}), <draconicevolution:draconium_capacitor:1>.withTag({DEUpgrades: {rfCap: 4 as byte}, Energy: 768000000}), <ore:blockDraconiumAwakened>, <thermalexpansion:capacitor:32000>.withTag({Energy: 25000000}), <ore:blockDraconiumAwakened>, <draconicevolution:draconium_capacitor:1>.withTag({DEUpgrades: {rfCap: 4 as byte}, Energy: 768000000}), <draconicevolution:draconium_capacitor>.withTag({DEUpgrades: {rfCap: 3 as byte}, Energy: 160000000}), <ore:blockCosmicNeutronium>], 
	[<avaritia:resource:6>, <ore:blockCosmicNeutronium>, <draconicevolution:draconium_capacitor>.withTag({DEUpgrades: {rfCap: 3 as byte}, Energy: 160000000}), <draconicevolution:draconium_capacitor:1>.withTag({DEUpgrades: {rfCap: 4 as byte}, Energy: 768000000}), <avaritia:resource:6>, <draconicevolution:draconium_capacitor:1>.withTag({DEUpgrades: {rfCap: 4 as byte}, Energy: 768000000}), <draconicevolution:draconium_capacitor>.withTag({DEUpgrades: {rfCap: 3 as byte}, Energy: 160000000}), <ore:blockCosmicNeutronium>, <avaritia:resource:6>]
]);