mods.extendedcrafting.TableCrafting.addShapedMirrored(0, <mysticalagradditions:stuff:69>, [
	[<mysticalagriculture:stone_essence>, <mysticalagriculture:nature_essence>, <mysticalagriculture:water_essence>, <mysticalagriculture:fire_essence>, <mysticalagriculture:nether_quartz_essence>, <mysticalagriculture:glowstone_essence>, <mysticalagriculture:redstone_essence>, <mysticalagriculture:obsidian_essence>, <mysticalagriculture:gold_essence>], 
	[<mysticalagriculture:lapis_lazuli_essence>, <mysticalagriculture:end_essence>, <mysticalagriculture:experience_essence>, <mysticalagriculture:diamond_essence>, <mysticalagriculture:emerald_essence>, <mysticalagriculture:slime_essence>, <mysticalagriculture:skeleton_essence>, <mysticalagriculture:creeper_essence>, <mysticalagriculture:spider_essence>], 
	[<mysticalagriculture:guardian_essence>, <mysticalagriculture:blaze_essence>, <mysticalagriculture:ghast_essence>, <mysticalagriculture:enderman_essence>, <mysticalagriculture:wither_skeleton_essence>, <mysticalagriculture:rubber_essence>, <mysticalagriculture:silicon_essence>, <mysticalagriculture:sulfur_essence>, <mysticalagriculture:zinc_essence>], 
	[<mysticalagriculture:brass_essence>, <mysticalagriculture:silver_essence>, <mysticalagriculture:lead_essence>, <mysticalagriculture:steel_essence>, <extendedcrafting:singularity_ultimate>, <mysticalagriculture:invar_essence>, <mysticalagriculture:mithril_essence>, <mysticalagriculture:tungsten_essence>, <mysticalagriculture:titanium_essence>], 
	[<mysticalagriculture:uranium_essence>, <mysticalagriculture:chrome_essence>, <mysticalagriculture:platinum_essence>, <extendedcrafting:singularity_ultimate>, <avaritia:resource:5>, <extendedcrafting:singularity_ultimate>, <mysticalagriculture:iridium_essence>, <mysticalagriculture:ruby_essence>, <mysticalagriculture:sapphire_essence>], 
	[<mysticalagriculture:peridot_essence>, <mysticalagriculture:amber_essence>, <mysticalagriculture:topaz_essence>, <mysticalagriculture:malachite_essence>, <extendedcrafting:singularity_ultimate>, <mysticalagriculture:tanzanite_essence>, <mysticalagriculture:blizz_essence>, <mysticalagriculture:blitz_essence>, <mysticalagriculture:basalz_essence>], 
	[<mysticalagriculture:signalum_essence>, <mysticalagriculture:lumium_essence>, <mysticalagriculture:enderium_essence>, <mysticalagriculture:hop_graphite_essence>, <mysticalagriculture:knightslime_essence>, <mysticalagriculture:ardite_essence>, <mysticalagriculture:cobalt_essence>, <mysticalagriculture:manyullyn_essence>, <mysticalagriculture:grains_of_infinity_essence>], 
	[<mysticalagriculture:soularium_essence>, <mysticalagriculture:dark_steel_essence>, <mysticalagriculture:vibrant_alloy_essence>, <mysticalagriculture:end_steel_essence>, <mysticalagriculture:elementium_essence>, <mysticalagriculture:terrasteel_essence>, <mysticalagriculture:void_metal_essence>, <mysticalagriculture:refined_obsidian_essence>, <mysticalagriculture:fiery_ingot_essence>], 
	[<mysticalagriculture:aquamarine_essence>, <mysticalagriculture:starmetal_essence>, <mysticalagriculture:ender_amethyst_essence>, <mysticalagriculture:draconium_essence>, <mysticalagriculture:yellorium_essence>, <mysticalagradditions:nether_star_essence>, <mysticalagradditions:dragon_egg_essence>, <mysticalagradditions:awakened_draconium_essence>, <mysticalagradditions:neutronium_essence>]
]);