mods.extendedcrafting.TableCrafting.addShaped(0, <avaritia:resource:5>, [
	[<extendedcrafting:material:7>, <extendedcrafting:material:7>, <extendedcrafting:material:7>, <extendedcrafting:material:7>, <extendedcrafting:material:7>, <extendedcrafting:material:7>, <extendedcrafting:material:7>, <extendedcrafting:material:7>, <extendedcrafting:material:7>], 
	[<extendedcrafting:material:7>, <openblocks:tank>.withTag({tank: {FluidName: "hot_spring_water", Amount: 16000}}), <openblocks:tank>.withTag({tank: {FluidName: "hot_spring_water", Amount: 16000}}), <openblocks:tank>.withTag({tank: {FluidName: "mana", Amount: 16000}}), <openblocks:tank>.withTag({tank: {FluidName: "mana", Amount: 16000}}), <openblocks:tank>.withTag({tank: {FluidName: "mana", Amount: 16000}}), <openblocks:tank>.withTag({tank: {FluidName: "flux_goo", Amount: 16000}}), <openblocks:tank>.withTag({tank: {FluidName: "flux_goo", Amount: 16000}}), <extendedcrafting:material:7>], 
	[<extendedcrafting:material:7>, <openblocks:tank>.withTag({tank: {FluidName: "hot_spring_water", Amount: 16000}}), <openblocks:tank>.withTag({tank: {FluidName: "experience", Amount: 16000}}), <ore:nuggetUltimate>, <ore:ingotCosmicNeutronium>, <ore:nuggetUltimate>, <openblocks:tank>.withTag({tank: {FluidName: "experience", Amount: 16000}}), <openblocks:tank>.withTag({tank: {FluidName: "flux_goo", Amount: 16000}}), <extendedcrafting:material:7>], 
	[<extendedcrafting:material:7>, <openblocks:tank>.withTag({tank: {FluidName: "ender", Amount: 16000}}), <ore:ingotCrystalMatrix>, <openblocks:tank>.withTag({tank: {FluidName: "pyrotheum", Amount: 16000}}), <openblocks:tank>.withTag({tank: {FluidName: "cryotheum", Amount: 16000}}), <openblocks:tank>.withTag({tank: {FluidName: "cryotheum", Amount: 16000}}), <avaritia:endest_pearl>, <openblocks:tank>.withTag({tank: {FluidName: "ender", Amount: 16000}}), <extendedcrafting:material:7>], 
	[<extendedcrafting:material:7>, <openblocks:tank>.withTag({tank: {FluidName: "ender", Amount: 16000}}), <ore:nuggetUltimate>, <openblocks:tank>.withTag({tank: {FluidName: "pyrotheum", Amount: 16000}}), <extendedcrafting:singularity_ultimate>, <openblocks:tank>.withTag({tank: {FluidName: "aerotheum", Amount: 16000}}), <ore:nuggetUltimate>, <openblocks:tank>.withTag({tank: {FluidName: "ender", Amount: 16000}}), <extendedcrafting:material:7>], 
	[<extendedcrafting:material:7>, <openblocks:tank>.withTag({tank: {FluidName: "ender", Amount: 16000}}), <avaritia:ultimate_stew>, <openblocks:tank>.withTag({tank: {FluidName: "petrotheum", Amount: 16000}}), <openblocks:tank>.withTag({tank: {FluidName: "petrotheum", Amount: 16000}}), <openblocks:tank>.withTag({tank: {FluidName: "aerotheum", Amount: 16000}}), <avaritia:resource:7>, <openblocks:tank>.withTag({tank: {FluidName: "ender", Amount: 16000}}), <extendedcrafting:material:7>], 
	[<extendedcrafting:material:7>, <openblocks:tank>.withTag({tank: {FluidName: "flux_goo", Amount: 16000}}), <openblocks:tank>.withTag({tank: {FluidName: "experience", Amount: 16000}}), <ore:nuggetUltimate>, <avaritia:cosmic_meatballs>, <ore:nuggetUltimate>, <openblocks:tank>.withTag({tank: {FluidName: "experience", Amount: 16000}}), <openblocks:tank>.withTag({tank: {FluidName: "hot_spring_water", Amount: 16000}}), <extendedcrafting:material:7>], 
	[<extendedcrafting:material:7>, <openblocks:tank>.withTag({tank: {FluidName: "flux_goo", Amount: 16000}}), <openblocks:tank>.withTag({tank: {FluidName: "flux_goo", Amount: 16000}}), <openblocks:tank>.withTag({tank: {FluidName: "mana", Amount: 16000}}), <openblocks:tank>.withTag({tank: {FluidName: "mana", Amount: 16000}}), <openblocks:tank>.withTag({tank: {FluidName: "mana", Amount: 16000}}), <openblocks:tank>.withTag({tank: {FluidName: "hot_spring_water", Amount: 16000}}), <openblocks:tank>.withTag({tank: {FluidName: "hot_spring_water", Amount: 16000}}), <extendedcrafting:material:7>], 
	[<extendedcrafting:material:7>, <extendedcrafting:material:7>, <extendedcrafting:material:7>, <extendedcrafting:material:7>, <extendedcrafting:material:7>, <extendedcrafting:material:7>, <extendedcrafting:material:7>, <extendedcrafting:material:7>, <extendedcrafting:material:7>]
]);